import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(SCRIPT_DIR, "..");
const portfolio = JSON.parse(fs.readFileSync(path.join(ROOT, "content", "portfolio.json"), "utf8"));
const contentDir = path.join(ROOT, "content", "sops");
const packs = fs.readdirSync(contentDir)
  .filter((name) => name.endsWith(".json"))
  .sort()
  .map((name) => JSON.parse(fs.readFileSync(path.join(contentDir, name), "utf8")));
const sops = packs.flatMap((pack) => pack.sops.map((sop) => ({ ...sop, app: pack.app, appName: pack.appName, sourceVersion: pack.sourceVersion })));
const sopById = new Map(sops.map((sop) => [sop.id, sop]));
const GENERATED_MARKER = "<!-- Generated by scripts/build.mjs; edit canonical JSON instead. -->\n";

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function list(items, className = "") {
  return `<ul${className ? ` class="${className}"` : ""}>${items.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>`;
}

function documentShell({ title, description, base = "", body, pageClass = "" }) {
  return `${GENERATED_MARKER}<!DOCTYPE html>
<html lang="th">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="${escapeHtml(description)}">
  <title>${escapeHtml(title)} | AKRA SOP</title>
  <link rel="icon" href="${base}assets/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="${base}styles/site.css">
</head>
<body class="${escapeHtml(pageClass)}">
  <a class="skip-link" href="#content">ข้ามไปเนื้อหา</a>
  <header class="site-header screen-only">
    <div class="header-inner">
      <a class="brand" href="${base}index.html">AKRA Frontline SOP</a>
      <nav class="site-nav" aria-label="เมนูคู่มือ">
        <a href="${base}index.html">คู่มือ</a>
        <a href="${base}inventory.html">ขอบเขตทุกระบบ</a>
      </nav>
    </div>
  </header>
${body}
  <footer class="site-footer screen-only">
    <div class="footer-inner"><p>ฉบับทดสอบภายใน · สร้างจาก canonical content เดียวสำหรับเว็บและ A5</p></div>
  </footer>
  <script src="${base}scripts/site.js" defer></script>
</body>
</html>
`;
}

function statusLabel(status) {
  if (status === "pilot-draft") return "ฉบับร่างสำหรับทดสอบ";
  if (status === "review-draft") return "ฉบับร่างสำหรับทบทวน";
  return status;
}

function accessLabel(access) {
  return access === "internal" ? "ใช้ภายใน" : access === "restricted" ? "จำกัดสิทธิ์" : access;
}

function renderResponse(response) {
  const items = Array.isArray(response)
    ? response
    : String(response || "").split("\n").filter(Boolean);
  return `<ol class="response-steps">${items.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ol>`;
}

function renderVisual(visual, sourceVersion, appLabel, calloutLabel) {
  const callout = visual.callout
    ? `<span class="callout" aria-hidden="true" style="--callout-top:${visual.callout.top};--callout-left:${visual.callout.left}">${escapeHtml(calloutLabel)}</span>`
    : "";
  const focuses = Array.isArray(visual.focuses) && visual.focuses.length
    ? `<div class="visual-focus-grid" aria-label="ภาพขยายจุดสำคัญ">
        ${visual.focuses.map((focus) => {
          const scale = Number(visual.width) / Number(focus.width);
          const left = -100 * Number(focus.x) / Number(focus.width);
          const top = -100 * Number(focus.y) / Number(focus.height);
          return `<div class="visual-focus">
            <p class="visual-focus-label">${escapeHtml(focus.label)}</p>
            <div class="visual-focus-window" style="--focus-ratio:${focus.width}/${focus.height};--focus-scale:${scale.toFixed(5)};--focus-left:${left.toFixed(5)}%;--focus-top:${top.toFixed(5)}%">
              <img src="../${escapeHtml(visual.src)}" alt="" width="${visual.width}" height="${visual.height}" loading="lazy">
            </div>
          </div>`;
        }).join("")}
      </div>`
    : "";
  return `<figure class="visual${focuses ? " visual--has-focus" : ""}">
    <div class="visual-frame">
      <img src="../${escapeHtml(visual.src)}" alt="${escapeHtml(visual.alt)}" width="${visual.width}" height="${visual.height}" loading="lazy">
      ${callout}
    </div>
    ${focuses}
    <figcaption>${escapeHtml(visual.caption)} <span class="visual-version">ภาพอ้างอิง ${escapeHtml(appLabel)} ${escapeHtml(sourceVersion)}</span></figcaption>
  </figure>`;
}

function renderSop(sop) {
  const related = (sop.related || []).map((id) => sopById.get(id)).filter(Boolean);
  const visualAppLabel = sop.app === "picking" ? "Picking" : String(sop.app || "").toUpperCase();
  const hasStopSection = Array.isArray(sop.stopAndEscalate) && sop.stopAndEscalate.length > 0;
  const steps = sop.steps.map((step, index) => `
    <li class="step${step.restricted ? " step--restricted" : ""}">
      ${step.role ? `<p class="step-role${step.restricted ? " step-role--restricted" : ""}">${escapeHtml(step.role)}</p>` : ""}
      <h3 class="step-title">${escapeHtml(step.title)}</h3>
      <p><strong>ทำ:</strong> ${escapeHtml(step.action)}</p>
      <p class="expected"><strong>เช็ก:</strong> ${escapeHtml(step.expected)}</p>
      ${renderVisual(step.visual, sop.sourceVersion, visualAppLabel, index + 1)}
    </li>`).join("");

  const problemDetails = sop.problems.map((problem) => {
    return `
    <details>
      <summary>${escapeHtml(problem.symptom)}</summary>
      <div class="details-content">
        ${renderResponse(problem.response)}
        ${problem.visual ? renderVisual(problem.visual, sop.sourceVersion, visualAppLabel, "!") : ""}
      </div>
    </details>`;
  }).join("");

  const printProblems = `<dl class="print-only print-problems">${sop.problems.map((problem) => {
    return `
    <div class="print-problem">
      <dt>${escapeHtml(problem.symptom)}</dt>
      <dd>
        ${renderResponse(problem.response)}
        ${problem.visual ? renderVisual(problem.visual, sop.sourceVersion, visualAppLabel, "!") : ""}
      </dd>
    </div>`;
  }).join("")}</dl>`;

  const relatedLinks = related.length
    ? `<ul>${related.map((item) => `<li><a href="${escapeHtml(item.slug)}.html">${escapeHtml(item.id)} · ${escapeHtml(item.title)}</a></li>`).join("")}</ul>`
    : "";
  const decisionGuide = Array.isArray(sop.decisions) && sop.decisions.length
    ? `<section aria-labelledby="decision-guide">
        <h2 id="decision-guide">เลือกเส้นทางจากข้อความที่เห็น</h2>
        <div class="table-scroll">
          <table class="decision-table">
            <thead><tr><th scope="col">ข้อความบนหน้าจอ</th><th scope="col">ความหมาย</th><th scope="col">ให้ทำต่อ</th></tr></thead>
            <tbody>${sop.decisions.map((decision) => `<tr><th scope="row">${escapeHtml(decision.symptom)}</th><td>${escapeHtml(decision.meaning)}</td><td>${escapeHtml(decision.response)}</td></tr>`).join("")}</tbody>
          </table>
        </div>
      </section>`
    : "";

  const tocPages = sop.tocPages || {};
  const tocItems = [
    ["prerequisites", "1", "เตรียมก่อนเริ่ม", tocPages.prerequisites || "3"],
    ["steps", "2", "ทำตามขั้นตอน", tocPages.steps || "3"],
    ["success", "3", "เช็กก่อนจบงาน", tocPages.success || "7"],
    ["problems", "4", "แก้ปัญหาที่พบบ่อย", tocPages.problems || "8"]
  ];
  if (hasStopSection) tocItems.push(["stop", "5", "หยุดและแจ้งหัวหน้า", tocPages.stop || "11"]);
  tocItems.push(["document-control", hasStopSection ? "6" : "5", "ข้อมูลเอกสาร", tocPages.documentControl || "11"]);
  const toc = `<nav class="book-toc" aria-labelledby="toc-title">
    <p class="section-kicker">เปิดหาเรื่องที่ต้องการได้ทันที</p>
    <h2 id="toc-title">สารบัญ</h2>
    <ol>${tocItems.map(([id, number, label, page]) => `<li>
      <a href="#${id}"><span class="toc-number">${number}</span><span class="toc-label">${escapeHtml(label)}</span><span class="toc-dots" aria-hidden="true"></span><span class="toc-page print-only">หน้า ${page}</span></a>
    </li>`).join("")}</ol>
  </nav>`;

  const documentControl = `
    <details class="document-control" id="document-control">
      <summary>ข้อมูลเอกสาร</summary>
      <div class="document-control-content">
        <dl class="meta-grid">
          <div class="meta-item"><dt>รหัสคู่มือ</dt><dd>${escapeHtml(sop.id)}</dd></div>
          <div class="meta-item"><dt>ฉบับเอกสาร</dt><dd>${escapeHtml(sop.revision)}</dd></div>
          <div class="meta-item"><dt>เวอร์ชันแอปที่ตรวจ</dt><dd>${escapeHtml(sop.sourceVersion)}</dd></div>
          <div class="meta-item"><dt>เจ้าของเนื้อหา</dt><dd>${escapeHtml(sop.owner)}</dd></div>
          <div class="meta-item"><dt>ผู้อนุมัติ</dt><dd>${escapeHtml(sop.approver)}</dd></div>
          <div class="meta-item"><dt>ตรวจล่าสุด</dt><dd>${escapeHtml(sop.reviewedOn || "รอตรวจโดยเจ้าของงาน")}</dd></div>
          <div class="meta-item"><dt>ตรวจครั้งถัดไป</dt><dd>${escapeHtml(sop.nextReviewOn || "กำหนดหลังอนุมัติรอบแรก")}</dd></div>
        </dl>
      </div>
    </details>`;

  const body = `
  <main id="content" class="page-shell" tabindex="-1">
    <article>
      <header class="sop-header">
        <p class="eyebrow">คู่มือพนักงาน · ${escapeHtml(sop.appName)}</p>
        <h1>${escapeHtml(sop.title)}</h1>
        <p class="lead">${escapeHtml(sop.purpose)}</p>
        <div class="badge-row" aria-label="สถานะเอกสาร">
          <span class="badge badge--draft">${escapeHtml(statusLabel(sop.status))}</span>
          <span class="badge badge--internal">${escapeHtml(accessLabel(sop.access))}</span>
          <span class="badge">ประมาณ ${sop.estimatedMinutes} นาที</span>
          <span class="badge">${escapeHtml(sop.audience)}</span>
        </div>
        <div class="badge-row screen-only">
          <a class="button" href="#steps">เริ่มทำตามขั้นตอน</a>
          <button class="button" type="button" data-print>พิมพ์ / บันทึก PDF A5</button>
          <a class="button button--secondary" href="../index.html">กลับหน้ารวม</a>
        </div>
        <p class="notice notice--draft"><strong>ฉบับทดสอบภายใน:</strong> ใช้ตรวจขั้นตอนและความเข้าใจก่อนประกาศใช้</p>
      </header>

      ${toc}

      <section class="prepare-section" aria-labelledby="prerequisites">
        <p class="section-kicker">ส่วนที่ 1</p>
        <h2 id="prerequisites">เตรียมก่อนเริ่ม</h2>
        ${list(sop.prerequisites)}
      </section>

      ${decisionGuide}

      <section aria-labelledby="steps">
        <p class="section-kicker">ส่วนที่ 2</p>
        <h2 id="steps">ทำตามขั้นตอน</h2>
        <ol class="step-list">${steps}</ol>
      </section>

      <section class="success-box" aria-labelledby="success">
        <p class="section-kicker">ส่วนที่ 3</p>
        <h2 id="success">เช็กก่อนจบงาน</h2>
        <p>งานเสร็จเมื่อครบทั้ง ${sop.successChecklist.length} ข้อ</p>
        ${list(sop.successChecklist || [])}
      </section>

      <section class="problem-list" aria-labelledby="problems">
        <p class="section-kicker">ส่วนที่ 4</p>
        <h2 id="problems">แก้ปัญหาที่พบบ่อย</h2>
        <p class="screen-only">เลือกข้อความที่ตรงกับหน้าจอ แล้วทำตามทีละข้อ</p>
        <div class="screen-only">${problemDetails}</div>
        ${printProblems}
      </section>

      ${hasStopSection ? `<section class="stop-box" aria-labelledby="stop">
        <p class="section-kicker">ส่วนที่ 5</p>
        <h2 id="stop">หยุดและแจ้งหัวหน้าเมื่อ</h2>
        ${list(sop.stopAndEscalate)}
      </section>` : ""}

      ${related.length ? `<section aria-labelledby="related"><h2 id="related">คู่มือที่เกี่ยวข้อง</h2>${relatedLinks}</section>` : ""}

      ${documentControl}
    </article>
  </main>`;

  return documentShell({
    title: `${sop.id} ${sop.title}`,
    description: sop.purpose,
    base: "../",
    body,
    pageClass: "sop-page"
  });
}

function renderIndex() {
  const cards = sops.map((sop) => {
    const searchText = [sop.id, sop.title, sop.audience, sop.purpose, ...sop.steps.map((step) => step.title)].join(" ");
    return `<article class="card" data-search-card="${escapeHtml(searchText)}">
      <p class="eyebrow">${escapeHtml(sop.id)} · ${escapeHtml(sop.appName)}</p>
      <h3><a href="sops/${escapeHtml(sop.slug)}.html">${escapeHtml(sop.title)}</a></h3>
      <p>${escapeHtml(sop.purpose)}</p>
      <p class="card-meta">${escapeHtml(sop.audience)} · ${sop.estimatedMinutes} นาที · ${escapeHtml(statusLabel(sop.status))}</p>
    </article>`;
  }).join("");

  const body = `
  <main id="content" class="page-shell" tabindex="-1">
    <section class="hero">
      <p class="eyebrow">Employee guidance · Local review</p>
      <h1>คู่มือทำงาน AKRA แบบสั้น ทำตามได้ทีละงาน</h1>
      <p class="lead">ค้นจากงานที่ต้องทำ อ่านผลที่ควรเห็น และหยุดเมื่อพบเงื่อนไขเสี่ยง เนื้อหาเว็บและ A5 มาจากแหล่งเดียวกันเพื่อลดคู่มือไม่ตรงกัน</p>
      <div class="badge-row">
        <span class="badge badge--draft">Handbook review ${escapeHtml(portfolio.libraryVersion)}</span>
        <span class="badge badge--internal">Local review only</span>
        <span class="badge">${sops.length} คู่มือ · ${sops.reduce((sum, sop) => sum + sop.steps.length, 0)} ขั้นตอนพร้อมภาพ</span>
      </div>
      <p class="notice"><strong>ยังไม่ประกาศใช้:</strong> รอเจ้าของงานตรวจข้อเท็จจริง ทดสอบกับพนักงาน และเลือกรูปแบบ public / Main SSO / mixed ก่อนเผยแพร่</p>
    </section>

    <search class="search-box">
      <label for="sop-search">ค้นหาคู่มือ งาน หรือสถานะ</label>
      <input id="sop-search" type="search" placeholder="เช่น ส่ง LINE ซ้ำ, ประวัติ, บิลด่วน" autocomplete="off" data-sop-search>
      <p class="card-meta" aria-live="polite" data-search-status>พบ ${sops.length} คู่มือ</p>
    </search>

    <section aria-labelledby="review-guides">
      <h2 id="review-guides">คู่มือพร้อมทบทวน</h2>
      <div class="card-grid">${cards}</div>
    </section>

    <section aria-labelledby="portfolio-scope">
      <h2 id="portfolio-scope">ขอบเขตทั้ง 9 แอป</h2>
      <p>คู่มือครบทั้ง 9 แอปแล้ว และอยู่ระหว่างทบทวนชื่อผู้รับผิดชอบ วันที่ตรวจ และรูปแบบการเผยแพร่</p>
      <a class="button button--secondary" href="inventory.html">ดู workflow inventory</a>
    </section>
  </main>`;

  return documentShell({
    title: "คู่มือพนักงาน",
    description: "คู่มือปฏิบัติงานภาษาไทยสำหรับ AKRA WEBAPP",
    body
  });
}

function renderInventory() {
  const rows = portfolio.packs.map((pack) => `<tr>
    <th scope="row">${escapeHtml(pack.name)}</th>
    <td>${escapeHtml(pack.sourceVersion)}</td>
    <td>${escapeHtml(pack.audiences.join(", "))}</td>
    <td>${escapeHtml(pack.ownerRole)}<br><span class="card-meta">อนุมัติ: ${escapeHtml(pack.approverRole)}</span></td>
    <td>${list(pack.workflows)}</td>
    <td>${escapeHtml(pack.verification)}</td>
  </tr>`).join("");

  const body = `
  <main id="content" class="page-shell" tabindex="-1">
    <header class="hero">
      <p class="eyebrow">Portfolio inventory</p>
      <h1>ขอบเขต workflow สำหรับ SOP ทั้ง 9 แอป</h1>
      <p class="lead">รายการนี้ใช้ตรวจว่า workflow ที่รองรับใน production ถูกนำไปทำ SOP หรือระบุ exclusion อย่างชัดเจน</p>
      <p class="notice"><strong>สถานะ:</strong> คู่มือทั้ง 9 แอปตรวจ source และภาพตัวอย่างปลอดภัยแล้ว รอเจ้าของงานและพนักงานทบทวนก่อนประกาศใช้</p>
    </header>
    <section aria-labelledby="inventory-table">
      <h2 id="inventory-table">Workflow inventory</h2>
      <div class="table-scroll">
        <table>
          <caption>อัปเดต ${escapeHtml(portfolio.updatedOn)} · รอบตรวจเสนอ ${portfolio.reviewCadenceDays} วัน</caption>
          <thead><tr><th scope="col">ระบบ</th><th scope="col">เวอร์ชัน</th><th scope="col">ผู้ใช้</th><th scope="col">เจ้าของ</th><th scope="col">Workflow</th><th scope="col">หลักฐาน</th></tr></thead>
          <tbody>${rows}</tbody>
        </table>
      </div>
    </section>
    <section aria-labelledby="exclusions">
      <h2 id="exclusions">ไม่รวมในแผนนี้</h2>
      ${list(portfolio.explicitExclusions)}
    </section>
  </main>`;

  return documentShell({
    title: "Workflow inventory",
    description: "ขอบเขต workflow สำหรับ SOP ของ AKRA WEBAPP ทั้งเก้าแอป",
    body
  });
}

const cleanOutput = (html) => html.replace(/[ \t]+$/gm, "");
const outputs = new Map([
  [path.join(ROOT, "index.html"), cleanOutput(renderIndex())],
  [path.join(ROOT, "inventory.html"), cleanOutput(renderInventory())],
  ...sops.map((sop) => [path.join(ROOT, "sops", `${sop.slug}.html`), cleanOutput(renderSop(sop))])
]);
const sopOutputDir = path.join(ROOT, "sops");
const checkOnly = process.argv.includes("--check");
const mismatches = [];

fs.mkdirSync(sopOutputDir, { recursive: true });
for (const [file, expected] of outputs) {
  if (checkOnly) {
    if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== expected) {
      mismatches.push(`${path.relative(ROOT, file)} is missing or stale`);
    }
  } else {
    fs.writeFileSync(file, expected, "utf8");
  }
}

const expectedSopFiles = new Set([...outputs.keys()].filter((file) => path.dirname(file) === sopOutputDir));
for (const name of fs.readdirSync(sopOutputDir).filter((entry) => entry.endsWith(".html"))) {
  const file = path.join(sopOutputDir, name);
  if (expectedSopFiles.has(file)) continue;
  const existing = fs.readFileSync(file, "utf8");
  if (checkOnly) {
    mismatches.push(`${path.relative(ROOT, file)} is an orphan generated page`);
  } else if (existing.startsWith(GENERATED_MARKER)) {
    fs.rmSync(file);
  } else {
    throw new Error(`Refusing to remove non-generated orphan ${path.relative(ROOT, file)}`);
  }
}

if (mismatches.length) {
  console.error("Generated output is not in sync with canonical content:");
  mismatches.forEach((mismatch) => console.error(`- ${mismatch}`));
  process.exit(1);
}

console.log(`${checkOnly ? "Checked" : "Built"} index, inventory, and ${sops.length} SOP pages.`);
